[package]
name = "learn"
version = "0.1.0"
edition = "2024"

[dependencies]
waker-fn = "1.1"
futures-lite = "2.5.0"
crossbeam = "0.8"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
surf = "2.3.1"
async-std = "1.10"